name: Test

defaults:
 run:
   shell: bash
    
on:
  workflow_dispatch:
  push:
    branches: [ main ]
env:
    AZURE_RESOURCE_GROUP: openhackztk992u0rg  # target resource, must match the {resource-group-name} you setup in the pre-requisties
    WEB_APP_NAME: openhackztk992u0trips         # set the name for the Web App on Azure
    CONTAINER_IMAGE_NAME: api-trips # set the name for the container image
    SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}  # connection string for the Azure SQL database -> must be in the secrets
    ACR_NAME: devopsoh               # set the name for the Azure Container Registry
    ACR_LOGIN_SERVER: openhackztk992u0acr.azurecr.io # fqdn for the Azure Container Registry
    ACR_USERNAME: ${{ secrets.ACR_USERNAME }} # user name for accessing Azure Container Registry
    ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }} # password for accesing the Azure Container Registry  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Health of Staging Env
      env:
          HEALTH_CHECK: $(curl -s --http2 -i https://openhackztk992u0trips-staging.azurewebsites.net/api/healthcheck/trips | tee >(grep -v "^{") | grep "^{" | jq -r '.status')
      run: |
        echo ${{env.HEALTH_CHECK}}
        if [ ${{env.HEALTH_CHECK}} = "sHealthy" ]
        then
            echo "Healthy"
            exit 0
        else
            echo "Not Healthy"
            exit 1
        fi
#       if: ${{ env.HEALTH_CHECK == 'Healthy' }}
#       run: echo "Staging is Healthy"

