name: Trips Go Module Docker push

#defaults:
#  run:
#    shell: bash
#    working-directory: apis/trips
    
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apis/trips/**'
  pull_request:
    branches: [ main ]
env:
    AZURE_RESOURCE_GROUP: openhackztk992u0rg  # target resource, must match the {resource-group-name} you setup in the pre-requisties
    WEB_APP_NAME: openhackztk992u0trips         # set the name for the Web App on Azure
    CONTAINER_IMAGE_NAME: api-trips # set the name for the container image
    SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}  # connection string for the Azure SQL database -> must be in the secrets
    ACR_NAME: devopsoh               # set the name for the Azure Container Registry
    ACR_LOGIN_SERVER: openhackztk992u0acr.azurecr.io # fqdn for the Azure Container Registry
    ACR_USERNAME: ${{ secrets.ACR_USERNAME }} # user name for accessing Azure Container Registry
    ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }} # password for accesing the Azure Container Registry  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
         registry: ${{ env.ACR_LOGIN_SERVER }}
         username: ${{ env.ACR_USERNAME }}
         password: ${{ env.ACR_PASSWORD }}
         logout: false

    - run: docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{env.ACR_NAME}}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }} --build-arg build_version=${{ github.run_id }} -f ./apis/trips/Dockerfile ./apis/trips
    - run: docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ env.ACR_USERNAME }} -p ${{ env.ACR_PASSWORD }}
    - run: docker push ${{ env.ACR_LOGIN_SERVER }}/${{env.ACR_NAME}}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackztk992u0trips'
        publish-profile: ${{ secrets.AZURE_WEBAPP_TRIPS_STAGING_PUBLISH_PROFILE }}
        images: ${{ env.ACR_LOGIN_SERVER }}/${{env.ACR_NAME}}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}

    - run: |
        response = $(curl -s --http2 -i https://openhackztk992u0trips-staging.azurewebsites.net/api/healthcheck/trips | tee >(grep -v "^{") | grep "^{" | jq -r '.status')         
        echo "response from curl= $response"

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to ACR
#       uses: docker/login-action@v1
#       with:
#           registry: ${{ env.ACR_LOGIN_SERVER }}
#           username: ${{ env.ACR_USERNAME }}
#           password: ${{ env.ACR_PASSWORD }}
#           logout: false
    

#     - name: Build and push container image to registry
#       uses: docker/build-push-action@v2
#       with:
#           #context: ./.devcontainer/
#           push: true
#           tags: ${{ env.ACR_LOGIN_SERVER }}/${{env.ACR_NAME}}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
#           file: ./apis/trips/Dockerfile
