# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: UserProfile

defaults:
  run:
    shell: bash
    working-directory: apis/userprofile
on:
 workflow_dispatch:
 push:
   branches: [main]
   paths:
      - 'apis/userprofile/**'
 pull_request:
   branches: [main]
env:
  AZURE_RESOURCE_GROUP: openhackztk992u0rg  # target resource, must match the {resource-group-name} you setup in the pre-requisties
  WEB_APP_NAME: UserProfile         # set the name for the Web App on Azure
  CONTAINER_IMAGE_NAME: devopsoh/api-userprofile # set the name for the container image
  #SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}  # connection string for the Azure SQL database -> must be in the secrets
  ACR_NAME: devopsoh               # set the name for the Azure Container Registry
  ACR_LOGIN_SERVER: openhackztk992u0acr.azurecr.io # fqdn for the Azure Container Registry
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }} # user name for accessing Azure Container Registry
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }} # password for accesing the Azure Container Registry
  AZURE_WEBAPP_NAME: MY_WEBAPP_NAME   # set this to your application's name
  AZURE_WEB_STAGE_PROFILE: ${{ secrets.AZURE_WEBAPP_USERPROFILE_STAGE_PUBLISH_PROFILE }}
  AZURE_WEB_PROD_PROFILE: ${{ secrets.AZURE_WEBAPP_USERPROFILE_PUBLISH_PROFILE }}
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
     
      - run: npm ci
      - run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
          logout: false
    

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
          file: ./apis/userprofile/Dockerfile
          
      
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackztk992u0userprofile'
          publish-profile: ${{ env.AZURE_WEB_STAGE_PROFILE }}
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
        
